version: '3.8'  # Specifies the Docker Compose version

services:
  backend:
    build: .
    container_name: my-backend
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    depends_on:
      - db  # Ensures database starts before backend
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb  # Connection string

  db:
    image: postgres:latest  # Use latest PostgreSQL image
    container_name: my-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data  # Persist data in a volume

volumes:
  db-data:  # Define named volume for PostgreSQL persistence