global:
   scripe_interval: 15

scrape_configs:
   - job_name: 'promotheus'
     static config:
        - target: [localhost:9090]

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['cadvisor:8080']

