name: CI/CD and Key Rotation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'
    
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      vault:
        image: vault:latest
        env:
          VAULT_DEV_ROOT_TOKEN_ID: myroot
          VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
        ports:
          - 8200:8200

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Setup Vault
      env:
        VAULT_ADDR: http://localhost:8200
        VAULT_TOKEN: myroot
      run: |
        vault secrets enable -path=secret kv-v2

    - name: Run tests
      working-directory: ./backend
      env:
        VAULT_ADDR: http://localhost:8200
        VAULT_TOKEN: myroot
      run: |
        pytest tests/ --cov=app

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ghcr.io/${{ github.repository }}/api-manager:latest
        
  rotate-key:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    
    steps:
    - name: Rotate API Key
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      run: |
        curl -X POST http://localhost:5000/api/rotate-key