# ansible-playbook -i inventory.ini -f 10 playbook.yml
# -f or --fork = demand number of execution

# inventory.yml
# [hosts]
# 10.250.33.231
# 10.250.33.8
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'python_app'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['localhost:9093']

rule_files:
  - 'alert_rules.yml'


global:
   scripe_interval: 15

scrape_configs:
   - job_name: 'promotheus'
     static config:
        - target: [localhost:9090]

   - job_name: 'node-exporter'
     static_configs:
      - targets: ['node-exporter:9100']

   - job_name: 'cAdvisor'
     static_configs:
      - targets: ['cadvisor:8080']

prometheus query :
  