name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Fetch API Key from Vault
      run: |
        chmod +x ./fetch_key.sh
        ./fetch_key.sh
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker

    - name: Build Docker Image
      run: |
        docker build --build-arg API_KEY=${{ env.API_KEY }} -t gcr.io/project1/job_processor:latest .

    - name: Push Docker Image
      run: docker push gcr.io/project1/job_processor:latest
